### ISSUE TITLE
Unable to deploy to production due to rails 5.0.1 conflict with bundler 2

### ISSUE THREAD

**Issue by jjmountain** [mhartl/action_cable_chat_app#24]
Rails 5.0.1, which the base app is made in, requires (bundler (< 2.0, >= 1.3.0)). However, the current bundler version is 2.0.1 which is not within this requirement. 

I tried uninstalling bundler with `gem uninstall bundler` and then installed the last version that should work with `gem install bundler --version 1.17.3`. That worked and I was able to bundle install successfully. 

However when I deploy to production in heroku it crashes half-way through installing the gems with this message in the terminal output:

Downloading rails-5.0.1 revealed dependencies not in the API or the lockfile
remote:        (bundler (< 2.0, >= 1.3.0)).
remote:        Either installing with `--full-index` or running `bundle update rails` should
remote:        fix the problem.

I reasoned that the problem was with the gemfile.lock, but altering it to bundler ( = 1.17.3) doesn't solve this problem.

I tried to use all my technical sophistication (over a number of hours this evening) but I can't work out how to resolve this so I can deploy to heroku. The only other thing I can think of is upgrading rails.. but when I searched for this the page I checked said that rails version needs to be decided when you create the app.

**Comment by jjmountain** [comment]
Also, running `bundle update rails` as the terminal output suggests has no effect, simply yielding the output: Bundler attempted to update rails but its version stayed the same

**Comment by mhartl** [comment]
I suggest trying this:

```
bundle _1.17.3_
```

That should tag the `Gemfile.lock` file with the version  of Bundler used:

```
BUNDLED WITH
   1.17.3
```

Subsequent calls to `bundle` should then automatically use the correct version of Bundler.

See [How to change the version of bundler being used in Rails?](https://stackoverflow.com/questions/36703644/how-to-change-the-version-of-bundler-being-used-in-rails) and [How to Upgrade to Bundler 2](https://bundler.io/guides/bundler_2_upgrade.html) for more information.

I’ve also recently updated [the application’s `Gemfile`](https://github.com/mhartl/action_cable_chat_app/blob/master/Gemfile), so you might want to see if using that helps as well.

**Comment by mhartl** [comment]
I’ve recently updated the app’s `Gemfile.lock` to use Bundler 2.
